export const CDN_PATH = 'https://3gimg.qq.com/lightmap/xcx/demoCenter/images';
export const COS_PATH = 'https://mapapi.qq.com/web/miniprogram/demoCenter/images';
export const PLUGIN_KEY = '24JBZ-VB6CV-HPBPV-U72XF-IHVY2-NXBOL';
export const MOYUAN_KEY = '24JBZ-VB6CV-HPBPV-U72XF-IHVY2-NXBOL';
export const BAIQIAN_KEY = '24JBZ-VB6CV-HPBPV-U72XF-IHVY2-NXBOL';
export const YULU_KEY = '24JBZ-VB6CV-HPBPV-U72XF-IHVY2-NXBOL';
export const DIFUNI_KEY = '';
export const INDOOR_KEY = '';
export const REFERER = '腾讯位置服务示例中心小程序';
export const WEBSERVICE_APPID = 'wxc1c68623b7bdea7b';
export const CUSTOM_KEY = ''; // 个性化地图key
